on: push
env:
  - BD_USER: root
  - BD_PASSWORD: root
  - BD_DATABASE: exemple
  - MySQL_HOST: localhost
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
     image: mysql:5.7
     port:
      - 3306:3306
     options: --health-cmd="mysqladmin ping" pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
     - name: Set up MySQL
       run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
     - name: Run tests
       run: python manage.py test
